SELECT DISTINCT ?_var1 (COUNT(DISTINCT ?_var2) AS ?_var3)
FROM <http://www.rdfabout.com/rdf/usgov/congress>
FROM <http://www.rdfabout.com/rdf/schema/Committees>
FROM <http://www.rdfabout.com/rdf/usgov/congress/people>
FROM <http://www.rdfabout.com/rdf/usgov/congress/99/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/100/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/101/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/102/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/103/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/104/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/105/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/106/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/107/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/108/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/109/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/110/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/111/bills>
FROM <http://www.rdfabout.com/rdf/usgov/congress/1/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/2/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/3/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/4/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/5/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/6/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/8/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/9/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/10/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/11/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/12/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/13/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/14/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/15/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/16/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/17/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/18/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/19/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/20/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/21/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/22/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/23/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/24/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/25/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/26/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/27/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/28/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/29/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/30/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/31/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/32/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/33/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/34/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/35/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/36/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/37/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/38/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/39/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/40/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/41/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/42/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/43/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/44/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/45/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/46/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/47/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/48/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/49/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/50/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/51/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/52/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/53/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/54/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/55/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/56/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/57/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/58/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/59/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/60/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/61/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/62/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/63/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/64/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/65/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/66/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/67/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/68/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/69/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/70/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/71/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/72/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/73/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/74/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/75/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/76/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/77/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/78/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/79/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/80/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/81/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/82/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/83/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/84/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/85/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/86/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/87/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/88/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/89/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/90/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/91/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/92/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/93/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/94/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/95/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/96/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/97/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/98/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/99/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/100/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/101/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/102/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/103/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/104/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/105/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/106/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/107/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/108/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/109/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/110/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/111/house>
FROM <http://www.rdfabout.com/rdf/usgov/congress/1/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/2/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/3/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/4/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/5/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/6/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/7/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/8/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/9/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/10/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/11/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/12/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/13/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/14/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/15/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/16/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/17/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/18/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/19/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/20/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/21/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/22/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/23/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/24/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/25/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/26/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/27/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/28/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/29/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/30/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/31/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/32/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/33/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/34/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/35/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/36/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/37/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/38/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/39/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/40/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/41/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/42/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/43/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/44/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/45/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/46/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/47/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/48/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/49/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/50/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/51/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/52/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/53/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/54/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/55/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/56/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/57/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/58/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/59/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/60/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/61/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/62/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/63/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/64/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/65/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/66/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/67/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/68/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/69/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/70/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/71/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/72/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/73/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/74/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/75/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/76/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/77/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/78/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/79/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/80/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/81/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/82/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/83/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/84/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/85/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/86/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/87/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/88/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/89/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/90/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/91/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/92/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/93/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/94/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/95/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/96/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/97/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/98/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/99/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/100/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/101/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/102/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/103/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/104/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/105/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/106/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/107/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/108/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/109/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/110/senate>
FROM <http://www.rdfabout.com/rdf/usgov/congress/111/senate>
 WHERE {
	?_var4 <http://www.rdfabout.com/rdf/schema/usbill/vote> ?_var2. 
	?_var5 <http://www.rdfabout.com/rdf/schema/usbill/hadAction> ?_var4. 
	?_var5 <http://www.rdfabout.com/rdf/schema/usbill/congress> ?_var1. 
	?_var2 <http://www.rdfabout.com/rdf/schema/vote/hasOption> ?_var6. 
	?_var2 <http://www.rdfabout.com/rdf/schema/vote/heldBy> ?_var7. 
	?_var7 <http://www.w3.org/2000/01/rdf-schema#label> "The United States Senate". 
	?_var2 <http://www.rdfabout.com/rdf/schema/vote/threshold> ?_var8. 
	?_var2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.rdfabout.com/rdf/schema/vote/Vote>
	FILTER (bound(?_var6))
	FILTER ((?_var8 in("3/5", "2/3")))
}
GROUP BY ?_var1
ORDER BY DESC(?_var3)
LIMIT 500