# Query producing 20968700 solutions before the DISTINCT.
#
# compare distinct01{a,b,c}

SELECT ?_var3 # 138802ms, 2M results (added time is materialization costs)
WHERE {
  GRAPH ?g {
    ?_var10 a <http://www.rdfabout.com/rdf/schema/vote/Option>. # 315k
    ?_var10 <http://www.rdfabout.com/rdf/schema/vote/votedBy> ?_var3 . #2M
  }
}
