# Default graph hash join with native DISTINCT SPO filter and index override. 
# 80s.  Note that the change to the native DISTINCT SPO filter to use the best
# possible index given the natural order of the source index did not impact the
# run time of this query nearly as much as it did hashjoin03b (this query now 
# runs in ~ 74s versus an original run time closer to 80s).

SELECT (COUNT(*) as ?count)
WHERE {
  ?_var10 a <http://www.rdfabout.com/rdf/schema/vote/Option>. # 315k, 300ms for AP scan.
  ?_var10 <http://www.rdfabout.com/rdf/schema/vote/votedBy> ?_var3 . #2M, 17623ms for AP scan.
  hint:Prior hint:hashJoin "true" . # use a hash join.
  hint:Prior hint:com.bigdata.bop.IPredicate.keyOrder "PCSO" . # use a specific index (default is POCS)
}
