# Named graph query with pipeline joins. 20968700 results.
# 20s with pipeline join.
#     [java] resultCount=1, elapsed=17194ms, source=queries/hashjoin02.rq
#     [java] resultCount=1, elapsed=17680ms, source=queries/hashjoin02.rq

SELECT (COUNT(*) as ?count)
WHERE{
  GRAPH ?g {
    ?_var10 a <http://www.rdfabout.com/rdf/schema/vote/Option>. # 315k, 300ms for AP scan.
    ?_var10 <http://www.rdfabout.com/rdf/schema/vote/votedBy> ?_var3 . #2M, 17623ms for AP scan.
  }
}
