# Named graph query with hash joins. 20968700 results.
# 60s with htree hash join and POCS index (default).

SELECT (COUNT(*) as ?count)
WHERE{
  GRAPH ?g {
    ?_var10 a <http://www.rdfabout.com/rdf/schema/vote/Option>. # 315k, 300ms for AP scan.
    ?_var10 <http://www.rdfabout.com/rdf/schema/vote/votedBy> ?_var3 . #2M, 17623ms for AP scan.
    hint:Prior hint:hashJoin "true" . # use a hash join.
  }
}
