# Converged run time of ~ 10000ms.
SELECT 
	?_var1 
	(GROUP_CONCAT(DISTINCT ?_var2 ; separator=";") AS ?_var3) 
	(GROUP_CONCAT(DISTINCT ?_var4 ; separator=";") AS ?_var5) 
	(GROUP_CONCAT(DISTINCT ?_var6 ; separator=";") AS ?_var7) 
	(GROUP_CONCAT(DISTINCT ?_var8 ; separator=";") AS ?_var9) 
	(GROUP_CONCAT(DISTINCT ?_var10 ; separator=";") AS ?_var11)

WITH {
	SELECT ?_var1
	WHERE {
		?_var1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.rdfabout.com/rdf/schema/politico/Politician>
	}
} AS %_set1
 WHERE {
	INCLUDE %_set1.
	OPTIONAL {
		?_var1 <http://www.w3.org/2001/vcard-rdf/3.0#BDAY> ?_var2
	}.
	OPTIONAL {
		?_var1 <http://www.rdfabout.com/rdf/schema/usgovt/name> ?_var6
	}.
	OPTIONAL {
		?_var1 <http://xmlns.com/foaf/0.1/religion> ?_var8
	}.
	OPTIONAL {
		?_var12 <http://www.rdfabout.com/rdf/schema/usbill/sponsor> ?_var1.
		?_var12 <http://www.rdfabout.com/rdf/schema/usbill/title> ?_var4
	}.
	OPTIONAL {
		?_var1 <http://www.w3.org/2001/vcard-rdf/3.0#N> ?_var13.
		?_var13 <http://www.w3.org/2001/vcard-rdf/3.0#Family> ?_var10
	}
}
GROUP BY ?_var1
ORDER BY ?_var1
LIMIT 500