/**

Copyright (C) SYSTAP, LLC 2006-2007.  All rights reserved.

Contact:
     SYSTAP, LLC
     4501 Tower Road
     Greensboro, NC 27410
     licenses@bigdata.com

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
/*
 * Created on Mar 18, 2007
 */

package com.bigdata.service;

import java.io.IOException;
import java.rmi.Remote;
import java.rmi.RemoteException;

/**
 * The public interface for a test service.
 * <p>
 * Note: The interface extends {@link Remote} so that both the implementation of
 * this service and the proxy generated by jeri for the service will implement
 * this interface. This is necessary for service discovery or the resulting
 * proxy will NOT implement the interface and both service discovery (based on
 * the interface name) and use of the interface via the proxy will fail.
 * 
 * @author <a href="mailto:thompsonbry@users.sourceforge.net">Bryan Thompson</a>
 * @version $Id$
 * @download
 */
public interface ITestService extends Remote 
{

    /**
     * Method for testing remote invocation.
     * <p>
     * Note: The methods on a {@link Remote} interface MUST throw
     * {@link RemoteException} (or {@link IOException} if you want to reduce
     * your dependency on JINI for an interface that is also used outside of
     * JINI).
     */
    public void invoke() throws RemoteException;
            
}
