name		'systap-bigdata'
maintainer	'Daniel Mekonnen'
maintainer_email 'daniel<no-spam-at>systap.com'
license		'All rights reserved'
description	'Installs/Configures systap-bigdata'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version		'0.1.0'
depends		'apt'
depends		'java'
depends		'tomcat'
