/*

Copyright (C) SYSTAP, LLC 2006-2008.  All rights reserved.

Contact:
     SYSTAP, LLC
     4501 Tower Road
     Greensboro, NC 27410
     licenses@bigdata.com

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
/*
 * Created on Aug 20, 2008
 */

package com.bigdata.rdf.rules;

import org.apache.log4j.Logger;

import com.bigdata.btree.IIndex;
import com.bigdata.btree.ITupleIterator;
import com.bigdata.journal.TemporaryStore;
import com.bigdata.rdf.inf.BackchainOwlSameAsPropertiesIterator;
import com.bigdata.rdf.inf.BackchainTypeResourceIterator;
import com.bigdata.rdf.spo.ISPO;
import com.bigdata.rdf.spo.SPORelation;
import com.bigdata.rdf.store.IRawTripleStore;
import com.bigdata.relation.accesspath.IAccessPath;
import com.bigdata.relation.accesspath.IElementFilter;
import com.bigdata.relation.rule.IPredicate;
import com.bigdata.relation.rule.IVariableOrConstant;
import com.bigdata.striterator.ChunkedWrappedIterator;
import com.bigdata.striterator.IChunkedIterator;
import com.bigdata.striterator.IChunkedOrderedIterator;
import com.bigdata.striterator.IKeyOrder;

/**
 * A read-only {@link IAccessPath} that backchains certain inferences.
 * <p>
 * Note: Low level methods may not behave quite as expected since some elements
 * will be generated by the backchainer and hence present in the underlying
 * {@link SPORelation}. See the notes on the various methods in the API for
 * more details.
 * 
 * @author <a href="mailto:thompsonbry@users.sourceforge.net">Bryan Thompson</a>
 * @version $Id$
 */
public class BackchainAccessPath implements IAccessPath<ISPO> {

    protected static transient final Logger log = Logger
            .getLogger(BackchainAccessPath.class);

    private final static transient long NULL = IRawTripleStore.NULL;

    final private InferenceEngine inf;
    final private TemporaryStore tempStore;
    final private IAccessPath<ISPO> accessPath;

    /**
     * 
     * @param inf
     * @param accessPath
     *            The source {@link IAccessPath}.
     */
    public BackchainAccessPath(InferenceEngine inf, IAccessPath<ISPO> accessPath) {

        if (inf == null)
            throw new IllegalArgumentException();
        
        if (accessPath == null)
            throw new IllegalArgumentException();

        this.inf = inf;
        
        this.accessPath = accessPath;
        
    }

    /**
     * The source {@link IAccessPath}.
     */
    final public IAccessPath<ISPO> getSource() {
        
        return accessPath;
        
    }
    
    /**
     * The {@link IIndex} for the source {@link IAccessPath}.
     */
    final public IIndex getIndex() {

        return accessPath.getIndex();
        
    }

    final public IKeyOrder<ISPO> getKeyOrder() {
        
        return accessPath.getKeyOrder();
        
    }

    final public IPredicate<ISPO> getPredicate() {
        
        return accessPath.getPredicate();
        
    }

    public boolean isEmpty() {
        
        final IChunkedIterator<ISPO> itr = iterator(1,1);
        
        try {
            
            return ! itr.hasNext();
            
        } finally {
            
            itr.close();
            
        }
        
    }

    /**
     * Visits elements in the source {@link IAccessPath} plus all entailments
     * licensed by the {@link InferenceEngine}.
     */
    public IChunkedOrderedIterator<ISPO> iterator() {
        
        return iterator(0,0);
        
    }

    /**
     * Visits elements in the source {@link IAccessPath} plus all entailments
     * licensed by the {@link InferenceEngine} as configured.
     */
    public IChunkedOrderedIterator<ISPO> iterator(int limit, int capacity) {

        if (log.isInfoEnabled()) {

            log.info(accessPath.getPredicate().toString());
            
        }
        
        // pass the limit and capacity through to the source access path.
        final IChunkedOrderedIterator<ISPO> src = accessPath.iterator(limit,
                capacity);
        
        final IChunkedOrderedIterator<ISPO> ret;

        final IPredicate<ISPO> predicate = accessPath.getPredicate();

        final long s, p, o;
        {

            final IVariableOrConstant<Long> t = predicate.get(0);

            s = t.isVar() ? NULL : t.get();

        }

        {

            final IVariableOrConstant<Long> t = predicate.get(1);

            p = t.isVar() ? NULL : t.get();

        }

        {

            final IVariableOrConstant<Long> t = predicate.get(2);

            o = t.isVar() ? NULL : t.get();

        }

        if (inf.rdfsOnly) {
            
            // no entailments.
            ret = null;
        
        } else if(inf.forwardChainOwlSameAsClosure && !inf.forwardChainOwlSameAsProperties) {
            
            ret = new BackchainOwlSameAsPropertiesIterator(//
                    src,//
                    s,p,o,//
                    inf.database, //
                    inf.owlSameAs.get(),
                    tempStore
                    );

        } else {
            
            // no entailments.
            ret = null;
            
        }
        
        /*
         * Wrap it up as a chunked iterator.
         * 
         * Note: If we are not adding any entailments then we just use the
         * source iterator directly.
         * 
         * @todo why is the filter being passed in here? Can the backchaining
         * iterators produce entailments that would violate the filter? If so,
         * then shouldn't the filter be applied by the backchainers themselves
         * so that they do not overgenerate? (This comment also applies for the
         * type resource backchainer, below).
         */

        final IElementFilter<ISPO> filter = predicate.getConstraint();
        
        IChunkedOrderedIterator<ISPO> itr = (ret == null ? src
                : new ChunkedWrappedIterator<ISPO>(ret,
                        capacity == 0 ? inf.database.queryBufferCapacity
                                : capacity, null/* keyOrder */, filter));

        if (!inf.forwardChainRdfTypeRdfsResource) {
            
            /*
             * Backchain (x rdf:type rdfs:Resource ).
             * 
             * @todo pass the filter in here also.
             */
            
            itr = new BackchainTypeResourceIterator(//
                    itr,//
                    s,p,o,//
                    inf.database, //
                    inf.rdfType.get(), //
                    inf.rdfsResource.get() //
                    );
            
        }

        return itr;
        
    }

    /**
     * When <code>exact == false</code> this does not count the backchained
     * entailments. When <code>exact == true</code> traverses the
     * {@link #iterator()} so as to produce an exact count of the #of elements
     * that would in fact be visited, which combines those from the database
     * with those generated dynamically (NOT efficient).
     */
    public long rangeCount(boolean exact) {

        if (!exact)
            return accessPath.rangeCount(exact);

        log.warn("Will materialize statements and generate inferences");
        
        final IChunkedIterator<ISPO> itr = iterator();

        long n = 0L;

        try {

            while (itr.hasNext()) {

                itr.hasNext();

                n++;

            }

        } finally {

            itr.close();

        }

        return n;
        
    }

    /**
     * Delegated to the source {@link IAccessPath} (does not visit any
     * entailments).
     */
    public ITupleIterator<ISPO> rangeIterator() {
        
        return accessPath.rangeIterator();
        
    }

    /**
     * Delegated to the source {@link IAccessPath}.
     */
    public long removeAll() {

        return accessPath.removeAll();
        
    }
    
}
