/**

The Notice below must appear in each file of the Source Code of any
copy you distribute of the Licensed Product.  Contributors to any
Modifications may add their own copyright notices to identify their
own contributions.

License:

The contents of this file are subject to the CognitiveWeb Open Source
License Version 1.1 (the License).  You may not copy or use this file,
in either source code or executable form, except in compliance with
the License.  You may obtain a copy of the License from

  http://www.CognitiveWeb.org/legal/license/

Software distributed under the License is distributed on an AS IS
basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.  See
the License for the specific language governing rights and limitations
under the License.

Copyrights:

Portions created by or assigned to CognitiveWeb are Copyright
(c) 2003-2003 CognitiveWeb.  All Rights Reserved.  Contact
information for CognitiveWeb is available at

  http://www.CognitiveWeb.org

Portions Copyright (c) 2002-2003 Bryan Thompson.

Acknowledgements:

Special thanks to the developers of the Jabber Open Source License 1.0
(JOSL), from which this License was derived.  This License contains
terms that differ from JOSL.

Special thanks to the CognitiveWeb Open Source Contributors for their
suggestions and support of the Cognitive Web.

Modifications:

*/
/*
 * Created on Sep 15, 2007
 */

package com.bigdata.util;

import junit.framework.TestCase;

/**
 * Test suite for {@link HybridTimestampFactory}.
 * 
 * @todo test ctor correct acceptance and correct rejection and internally
 *       computed fields.
 * 
 * @todo test with all legal ctor values for counterBits and plot the #of
 *       distinct timestamps per millisecond as a function of counterBits.
 * 
 * @author <a href="mailto:thompsonbry@users.sourceforge.net">Bryan Thompson</a>
 * @version $Id$
 */
public class TestHybridTimestampFactory extends TestCase {

    /**
     * 
     */
    public TestHybridTimestampFactory() {
        super();
    }

    /**
     * @param arg0
     */
    public TestHybridTimestampFactory(String arg0) {
        super(arg0);
    }

    /**
     * Test verifies that timestamps are always distinct from the last generated
     * timestamp as generated by {@link HybridTimestampFactory#nextMillis()} and
     * notes the actual granularity of the generated timestamps.
     */
    public void test_nextTimestamp2() {

        final int limit = 100000;
        
        HybridTimestampFactory timestampFactory = new HybridTimestampFactory(10);
        
        final long begin = System.currentTimeMillis();

        long lastTimestamp = begin - 1;
        
        long timestamp;
        
        for( int i=0; i<limit; i++ ) {

            timestamp = timestampFactory.nextTimestamp();
            
            if (timestamp == lastTimestamp)
                fail("Same timestamp?");

            if (timestamp < lastTimestamp)
                fail("Time goes backwards?");

            lastTimestamp = timestamp;
            
        }
        
        long elapsed = System.currentTimeMillis() - begin;
        
        System.err.println("Generated " + limit + " timestamps in " + elapsed
                + " milliseconds: ts/ms: " + limit / (double) elapsed);
        
        System.err.println("The #of times the factory invoked Thread.sleep(): "
                + timestampFactory.getSleepCounter());
        
    }
    
}
