/* Generated By:JJTree: Do not edit this line. ASTUnparsedQuadDataBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bigdata.rdf.sail.sparql.ast;

public
class ASTUnparsedQuadDataBlock extends SimpleNode {
	
	private String dataBlock;
	
  public ASTUnparsedQuadDataBlock(int id) {
    super(id);
  }

  public ASTUnparsedQuadDataBlock(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }

  public void setDataBlock(String dataBlock) {
	  this.dataBlock = dataBlock;
  }
  
  public String getDataBlock() {
	  return dataBlock;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=18136156413f42ef82c335b36328e255 (do not edit this line) */
