/* Generated By:JavaCC: Do not edit this line. SyntaxTreeBuilderTreeConstants.java Version 5.0 */
package com.bigdata.rdf.sail.sparql.ast;

public interface SyntaxTreeBuilderTreeConstants
{
  public int JJTUPDATESEQUENCE = 0;
  public int JJTUPDATECONTAINER = 1;
  public int JJTQUERYCONTAINER = 2;
  public int JJTVOID = 3;
  public int JJTBASEDECL = 4;
  public int JJTPREFIXDECL = 5;
  public int JJTSELECTQUERY = 6;
  public int JJTSELECT = 7;
  public int JJTPROJECTIONELEM = 8;
  public int JJTCONSTRUCTQUERY = 9;
  public int JJTCONSTRUCT = 10;
  public int JJTDESCRIBEQUERY = 11;
  public int JJTDESCRIBE = 12;
  public int JJTASKQUERY = 13;
  public int JJTNAMEDSUBQUERY = 14;
  public int JJTDATASETCLAUSE = 15;
  public int JJTWHERECLAUSE = 16;
  public int JJTBINDINGSCLAUSE = 17;
  public int JJTBINDINGSET = 18;
  public int JJTBINDINGVALUE = 19;
  public int JJTGROUPCLAUSE = 20;
  public int JJTORDERCLAUSE = 21;
  public int JJTGROUPCONDITION = 22;
  public int JJTHAVINGCLAUSE = 23;
  public int JJTORDERCONDITION = 24;
  public int JJTLIMIT = 25;
  public int JJTOFFSET = 26;
  public int JJTGRAPHPATTERNGROUP = 27;
  public int JJTBASICGRAPHPATTERN = 28;
  public int JJTNAMEDSUBQUERYINCLUDE = 29;
  public int JJTOPTIONALGRAPHPATTERN = 30;
  public int JJTGRAPHGRAPHPATTERN = 31;
  public int JJTUNIONGRAPHPATTERN = 32;
  public int JJTMINUSGRAPHPATTERN = 33;
  public int JJTSERVICEGRAPHPATTERN = 34;
  public int JJTCONSTRAINT = 35;
  public int JJTFUNCTIONCALL = 36;
  public int JJTTRIPLESSAMESUBJECT = 37;
  public int JJTPROPERTYLIST = 38;
  public int JJTOBJECTLIST = 39;
  public int JJTTRIPLESSAMESUBJECTPATH = 40;
  public int JJTPROPERTYLISTPATH = 41;
  public int JJTPATHALTERNATIVE = 42;
  public int JJTPATHSEQUENCE = 43;
  public int JJTPATHELT = 44;
  public int JJTIRI = 45;
  public int JJTPATHONEINPROPERTYSET = 46;
  public int JJTPATHMOD = 47;
  public int JJTBLANKNODEPROPERTYLIST = 48;
  public int JJTCOLLECTION = 49;
  public int JJTVAR = 50;
  public int JJTOR = 51;
  public int JJTAND = 52;
  public int JJTCOMPARE = 53;
  public int JJTINFIX = 54;
  public int JJTMATH = 55;
  public int JJTNOT = 56;
  public int JJTNUMERICLITERAL = 57;
  public int JJTCOUNT = 58;
  public int JJTSUM = 59;
  public int JJTMIN = 60;
  public int JJTMAX = 61;
  public int JJTAVG = 62;
  public int JJTSAMPLE = 63;
  public int JJTGROUPCONCAT = 64;
  public int JJTMD5 = 65;
  public int JJTSHA1 = 66;
  public int JJTSHA224 = 67;
  public int JJTSHA256 = 68;
  public int JJTSHA384 = 69;
  public int JJTSHA512 = 70;
  public int JJTNOW = 71;
  public int JJTYEAR = 72;
  public int JJTMONTH = 73;
  public int JJTDAY = 74;
  public int JJTHOURS = 75;
  public int JJTMINUTES = 76;
  public int JJTSECONDS = 77;
  public int JJTTIMEZONE = 78;
  public int JJTTZ = 79;
  public int JJTRAND = 80;
  public int JJTABS = 81;
  public int JJTCEIL = 82;
  public int JJTFLOOR = 83;
  public int JJTROUND = 84;
  public int JJTSUBSTR = 85;
  public int JJTSTRLEN = 86;
  public int JJTUPPERCASE = 87;
  public int JJTLOWERCASE = 88;
  public int JJTSTRSTARTS = 89;
  public int JJTSTRENDS = 90;
  public int JJTSTRBEFORE = 91;
  public int JJTSTRAFTER = 92;
  public int JJTREPLACE = 93;
  public int JJTCONCAT = 94;
  public int JJTCONTAINS = 95;
  public int JJTENCODEFORURI = 96;
  public int JJTIF = 97;
  public int JJTIN = 98;
  public int JJTNOTIN = 99;
  public int JJTCOALESCE = 100;
  public int JJTSTR = 101;
  public int JJTLANG = 102;
  public int JJTLANGMATCHES = 103;
  public int JJTDATATYPE = 104;
  public int JJTBOUND = 105;
  public int JJTSAMETERM = 106;
  public int JJTISIRI = 107;
  public int JJTISBLANK = 108;
  public int JJTISLITERAL = 109;
  public int JJTISNUMERIC = 110;
  public int JJTBNODEFUNC = 111;
  public int JJTIRIFUNC = 112;
  public int JJTSTRDT = 113;
  public int JJTSTRLANG = 114;
  public int JJTBIND = 115;
  public int JJTLET = 116;
  public int JJTREGEXEXPRESSION = 117;
  public int JJTEXISTSFUNC = 118;
  public int JJTNOTEXISTSFUNC = 119;
  public int JJTRDFLITERAL = 120;
  public int JJTTRUE = 121;
  public int JJTFALSE = 122;
  public int JJTSTRING = 123;
  public int JJTQNAME = 124;
  public int JJTBLANKNODE = 125;
  public int JJTGRAPHREFALL = 126;
  public int JJTGRAPHORDEFAULT = 127;
  public int JJTQUADSNOTTRIPLES = 128;
  public int JJTLOAD = 129;
  public int JJTCLEAR = 130;
  public int JJTDROP = 131;
  public int JJTADD = 132;
  public int JJTMOVE = 133;
  public int JJTCOPY = 134;
  public int JJTCREATE = 135;
  public int JJTINSERTDATA = 136;
  public int JJTDELETEDATA = 137;
  public int JJTDELETEWHERE = 138;
  public int JJTDELETECLAUSE = 139;
  public int JJTINSERTCLAUSE = 140;
  public int JJTMODIFY = 141;


  public String[] jjtNodeName = {
    "UpdateSequence",
    "UpdateContainer",
    "QueryContainer",
    "void",
    "BaseDecl",
    "PrefixDecl",
    "SelectQuery",
    "Select",
    "ProjectionElem",
    "ConstructQuery",
    "Construct",
    "DescribeQuery",
    "Describe",
    "AskQuery",
    "NamedSubquery",
    "DatasetClause",
    "WhereClause",
    "BindingsClause",
    "BindingSet",
    "BindingValue",
    "GroupClause",
    "OrderClause",
    "GroupCondition",
    "HavingClause",
    "OrderCondition",
    "Limit",
    "Offset",
    "GraphPatternGroup",
    "BasicGraphPattern",
    "NamedSubqueryInclude",
    "OptionalGraphPattern",
    "GraphGraphPattern",
    "UnionGraphPattern",
    "MinusGraphPattern",
    "ServiceGraphPattern",
    "Constraint",
    "FunctionCall",
    "TriplesSameSubject",
    "PropertyList",
    "ObjectList",
    "TriplesSameSubjectPath",
    "PropertyListPath",
    "PathAlternative",
    "PathSequence",
    "PathElt",
    "IRI",
    "PathOneInPropertySet",
    "PathMod",
    "BlankNodePropertyList",
    "Collection",
    "Var",
    "Or",
    "And",
    "Compare",
    "Infix",
    "Math",
    "Not",
    "NumericLiteral",
    "Count",
    "Sum",
    "Min",
    "Max",
    "Avg",
    "Sample",
    "GroupConcat",
    "MD5",
    "SHA1",
    "SHA224",
    "SHA256",
    "SHA384",
    "SHA512",
    "Now",
    "Year",
    "Month",
    "Day",
    "Hours",
    "Minutes",
    "Seconds",
    "Timezone",
    "Tz",
    "Rand",
    "Abs",
    "Ceil",
    "Floor",
    "Round",
    "Substr",
    "StrLen",
    "UpperCase",
    "LowerCase",
    "StrStarts",
    "StrEnds",
    "StrBefore",
    "StrAfter",
    "Replace",
    "Concat",
    "Contains",
    "EncodeForURI",
    "If",
    "In",
    "NotIn",
    "Coalesce",
    "Str",
    "Lang",
    "LangMatches",
    "Datatype",
    "Bound",
    "SameTerm",
    "IsIRI",
    "IsBlank",
    "IsLiteral",
    "IsNumeric",
    "BNodeFunc",
    "IRIFunc",
    "StrDt",
    "StrLang",
    "Bind",
    "Let",
    "RegexExpression",
    "ExistsFunc",
    "NotExistsFunc",
    "RDFLiteral",
    "True",
    "False",
    "String",
    "QName",
    "BlankNode",
    "GraphRefAll",
    "GraphOrDefault",
    "QuadsNotTriples",
    "Load",
    "Clear",
    "Drop",
    "Add",
    "Move",
    "Copy",
    "Create",
    "InsertData",
    "DeleteData",
    "DeleteWhere",
    "DeleteClause",
    "InsertClause",
    "Modify",
  };
}
/* JavaCC - OriginalChecksum=e613af870e13fab19e7da05eb119c82b (do not edit this line) */
