#!/bin/bash

##
# Script brings up the bigdata services on a host.
#

# Setup the environment.
cd `dirname $0`
source ./bigdataenv

# Verify critical environment variables.
if [ -z "$lockFile" ]; then
    echo $"`date` : hostname : environment not setup."
    exit 1;
fi
if [ -z "$pidFile" ]; then
    echo $"`date` : hostname : environment not setup."
    exit 1;
fi
if [ -z "$LAS" ]; then
    echo $"`date` : hostname : environment not setup."
    exit 1;
fi
if [ -z "$JAVA_OPTS" ]; then
    echo $"`date` : hostname : environment not setup."
    exit 1;
fi
if [ -z "$BIGDATA_CONFIG" ]; then
    echo $"`date` : hostname : environment not setup."
    exit 1;
fi

if [ -f "$pidFile" ]; then
    echo $"`date` : `hostname` : process running? $pidFile."
    exit 1;
fi

# Create the subsystem lock file IFF it does not exist.
lockfile -r 1 -1 "$lockFile"
if [ 0 != $? ]; then
    echo $"`date` : `hostname` : could not obtain lock."
    exit 1;
fi
echo $"`date` : `hostname` : created lock file."

# Create a local directory in which to execute the services and within
# which they will store their persistent state.
if [ ! -d "$LAS" ]; then
    echo $"`date` : `hostname` : creating data directory."
    mkdir "$LAS"
fi

# Start the services manager on this host.
java ${JAVA_OPTS} \
	 com.bigdata.jini.start.ServicesManagerServer \
	 ${BIGDATA_CONFIG} ${BIGDATA_CONFIG_OVERRIDES} &

pid=$!

# Save the pid on a file and mark as read-only.
echo $pid > "$pidFile"
chmod ugo-w "$pidFile"

echo $"`date` : `hostname` : running : pid=$pid"

exit 0
