# SERVICE with one optional and a nested SERVICE. This query depends in the capabilities of the example1.org endpoint

PREFIX : <http://example.org/> 

SELECT ?s ?o1 ?o2
{
  SERVICE <http://localhost:18080/openrdf/repositories/endpoint1> {
  ?s ?p ?o1 .
  OPTIONAL {
	SERVICE <http://localhost:18080/openrdf/repositories/endpoint2> {
    ?s ?p2 ?o2 }
  }
}
}