
[query4]
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ub: <http://www.lehigh.edu/~zhp2/2004/0401/univ-bench.owl#>
SELECT ?x ?y1 ?y2 ?y3
WHERE{
	?x a ub:Professor;
		ub:worksFor <http://www.Department0.University0.edu>;
		ub:name ?y1;
		ub:emailAddress ?y2;
		ub:telephone ?y3.
}
