/* Generated By:JJTree: Do not edit this line. ASTBound.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTBound extends SimpleNode {

	public ASTBound(int id) {
		super(id);
	}

	public ASTBound(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public ASTVar getArg() {
		return (ASTVar)jjtGetChild(0);
	}
}
