/* Generated By:JJTree: Do not edit this line. ASTBlankNodePropertyList.java */

package org.openrdf.query.parser.sparql.ast;

public class ASTBlankNodePropertyList extends SimpleNode {

	private String varName;

	public ASTBlankNodePropertyList(int id) {
		super(id);
	}

	public ASTBlankNodePropertyList(SyntaxTreeBuilder p, int id) {
		super(p, id);
	}

	@Override
	public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data)
		throws VisitorException
	{
		return visitor.visit(this, data);
	}

	public String getVarName() {
		return varName;
	}

	public void setVarName(String varName) {
		this.varName = varName;
	}

	@Override
	public String toString()
	{
		return super.toString() + " (" + varName + ")";
	}
}