/* Generated By:JJTree: Do not edit this line. ASTNamedSubqueryInclude.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.openrdf.query.parser.sparql.ast;

public
class ASTNamedSubqueryInclude extends SimpleNode {
  public ASTNamedSubqueryInclude(int id) {
    super(id);
  }

  public ASTNamedSubqueryInclude(SyntaxTreeBuilder p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(SyntaxTreeBuilderVisitor visitor, Object data) throws VisitorException {
    return visitor.visit(this, data);
  }
  
  private String name;
  public void setName(String name) {
      this.name = name;
  }
  
  public String getName() {
      return name;
  }

}
/* JavaCC - OriginalChecksum=3c3697c969e7c8627c4e939334b4599f (do not edit this line) */
