#!/bin/sh
#
# /etc/init.d/blazegraph -- startup script for Blazegraph
#
# Modified from the tomcat7 script
# Written by Miquel van Smoorenburg <miquels@cistron.nl>.
# Modified for Debian GNU/Linux	by Ian Murdock <imurdock@gnu.ai.mit.edu>.
# Modified for Tomcat by Stefan Gybas <sgybas@debian.org>.
# Modified for Tomcat6 by Thierry Carrez <thierry.carrez@ubuntu.com>.
# Modified for Tomcat7 by Ernesto Hernandez-Novich <emhn@itverx.com.ve>.
# Additional improvements by Jason Brittain <jason.brittain@mulesoft.com>.
#
### BEGIN INIT INFO
# Provides:          blazegraph
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Blazegraph
# Description:       Start the Blazegraph High Performance Database.
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=blazegraph
DESC="Blazegraph High Performance Database"
DEFAULT=/etc/default/$NAME
JVM_TMP=/tmp/blazegraph-$NAME-tmp

if [ `id -u` -ne 0 -a "$1" != "status" ]; then
	echo "You need root privileges to run this script"
	exit 1
fi

# Make sure blazegraph is started with system locale
if [ -r /etc/default/locale ]; then
	. /etc/default/locale
	export LANG
fi

. /lib/lsb/init-functions

[ -r /etc/default/rcS ] && . /etc/default/rcS


# The following variables can be overwritten in $DEFAULT

# this is a work-around until there is a suitable runtime replacement
# for dpkg-architecture for arch:all packages
# this function sets the variable OPENJDKS
find_openjdks()
{
        for jvmdir in /usr/lib/jvm/java-7-openjdk-*
        do
                if [ -d "${jvmdir}" -a "${jvmdir}" != "/usr/lib/jvm/java-7-openjdk-common" ]
                then
                        OPENJDKS=$jvmdir
                fi
        done
        for jvmdir in /usr/lib/jvm/java-6-openjdk-*
        do
                if [ -d "${jvmdir}" -a "${jvmdir}" != "/usr/lib/jvm/java-6-openjdk-common" ]
                then
                        OPENJDKS="${OPENJDKS} ${jvmdir}"
                fi
        done
}

OPENJDKS=""
find_openjdks
# The first existing directory is used for JAVA_HOME (if JAVA_HOME is not
# defined in $DEFAULT)
JDK_DIRS="/usr/lib/jvm/default-java ${OPENJDKS} /usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-8-oracle"

# Look for the right JVM to use
for jdir in $JDK_DIRS; do
    [ -r "$jdir/bin/java" -a -z "${JAVA_HOME}" ] && JAVA_HOME="$jdir"
done
export JAVA_HOME

# Directory where the Tomcat 6 binary distribution resides
[ -z "$BLZG_HOME" ] && BLZG_HOME=/usr/share/$NAME

# Directory for per-instance configuration files and webapps
[ -z "$BLZG_BASE" ] && BLZG_BASE=$BLZG_HOME

# Use the Java security manager? (yes/no)
BLZG_SECURITY=no

# Default Java options
# Set java.awt.headless=true if JAVA_OPTS is not set so the
# Xalan XSL transformer can work without X11 display on JDK 1.4+
# It also looks like the default heap size of 64M is not enough for most cases
# so the maximum heap size is set to 128M
[ -z "$JAVA_OPTS" ] && JAVA_OPTS="-Djava.awt.headless=true -Xmx128M"

# End of variables that can be overwritten in $DEFAULT

# overwrite settings from default file
[ -f "$DEFAULT" ] && . "$DEFAULT"

[ -z "$BLZG_SH" ] && BLZG_SH="/usr/bin/blazegraph"
if [ ! -f "$BLZG_SH" ]; then
	log_failure_msg "$NAME is not installed"
	exit 1
fi

#POLICY_CACHE="$BLZG_BASE/work/catalina.policy"

[ -z "$BLZG_TMPDIR" ] && BLZG_TMPDIR="$JVM_TMP"

# Set the JSP compiler if set in the blazegraph.default file
[ -n "$JSP_COMPILER" ] && JAVA_OPTS="$JAVA_OPTS -Dbuild.compiler=\"$JSP_COMPILER\""

SECURITY=""
[ "$BLZG_SECURITY" = "yes" ] && SECURITY="-security"

# Define other required variables
BLZG_PID="/var/run/$NAME.pid"

# Look for Java Secure Sockets Extension (JSSE) JARs
[ -z "${JSSE_HOME}" -a -r "${JAVA_HOME}/jre/lib/jsse.jar" ] && JSSE_HOME="${JAVA_HOME}/jre/"

blazegraph_sh() {
	# Escape any double quotes in the value of JAVA_OPTS
	JAVA_OPTS="$(echo $JAVA_OPTS | sed 's/\"/\\\"/g')"

	# Define the command to run Tomcat's blazegraph.sh as a daemon
	# set -a tells sh to export assigned variables to spawned shells.
	# TODO: BLZG_TMPDIR is unused in downstream script
	# TODO: JAVA_OPTS is overwritten in downstream script
	# TODO: LOGGING_CONFIG is used in downstream script, but never defined even in $DEFAULT
	#       nor is there a logging.properties file packaged.
	BLZGCMD_SH="set -a;
		JAVA_HOME=\"$JAVA_HOME\"; \
		source \"$DEFAULT\"; \
		BLZG_HOME=\"$BLZG_HOME\"; \
		JAVA_OPTS=\"$JAVA_OPTS\"; \
		BLZG_PID=\"$BLZG_PID\"; \
		BLZG_LOG=\"$BLZG_LOG\"/blazegraph.log; \
		BLZG_TMPDIR=\"$BLZG_TMPDIR\"; \
		LANG=\"$LANG\"; \
		JSSE_HOME=\"$JSSE_HOME\"; \
		\"$BLZG_SH\" $@"

	AUTHBIND_COMMAND=""
	if [ "$AUTHBIND" = "yes" -a "$1" = "start" ]; then
		AUTHBIND_COMMAND="/usr/bin/authbind --deep /bin/bash -c "
		BLZGCMD_SH="'$BLZGCMD_SH'"
	fi

	# Run the blazegraph.sh script as a daemon
	set +e
	touch "$BLZG_PID" "$BLZG_LOG"/${NAME}.log
	chown $BLZG_USER "$BLZG_PID" "$BLZG_LOG"/${NAME}.log
	start-stop-daemon --start -b -u "$BLZG_USER" -g "$BLZG_GROUP" \
		-c "$BLZG_USER" -d "$BLZG_BASE" -p "$BLZG_PID" \
		-x /bin/bash -- -c "$AUTHBIND_COMMAND $BLZGCMD_SH"
	status="$?"
	set +a -e
	return $status
}

case "$1" in
  start)
	if [ -z "$JAVA_HOME" ]; then
		log_failure_msg "no JDK or JRE found - please set JAVA_HOME"
		exit 1
	fi

	if [ ! -d "$BLZG_CONF" ]; then
		log_failure_msg "invalid BLZG_CONF: $BLZG_CONF"
		exit 1
	fi

	log_daemon_msg "Starting $DESC" "$NAME"
	if start-stop-daemon --test --start --pidfile "$BLZG_PID" \
		--user $BLZG_USER --exec "$JAVA_HOME/bin/java" \
		>/dev/null; then

		# Regenerate POLICY_CACHE file
		#	umask 022
		#	echo "// AUTO-GENERATED FILE from /etc/blazegraph/policy.d/" \
		#		> "$POLICY_CACHE"
		#	echo ""  >> "$POLICY_CACHE"
		#	cat $BLZG_CONF/policy.d/*.policy \
		#		>> "$POLICY_CACHE"

		# Remove / recreate JVM_TMP directory
		rm -rf "$JVM_TMP"
		mkdir -p "$JVM_TMP" || {
			log_failure_msg "could not create JVM temporary directory"
			exit 1
		}
		chown $BLZG_USER "$JVM_TMP"

		blazegraph_sh start $SECURITY
		sleep 5
		if start-stop-daemon --test --start --pidfile "$BLZG_PID" \
			--user $BLZG_USER --exec "$JAVA_HOME/bin/java" \
			>/dev/null; then
			if [ -f "$BLZG_PID" ]; then
				rm -f "$BLZG_PID"
			fi
			log_end_msg 1
		else
			log_end_msg 0
		fi
	else
        log_progress_msg "(already running)"
		log_end_msg 0
	fi
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"

	set +e
	if [ -f "$BLZG_PID" ]; then
		start-stop-daemon --stop --pidfile "$BLZG_PID" \
			--user "$BLZG_USER" \
			--retry=TERM/20/KILL/5 >/dev/null
		if [ $? -eq 1 ]; then
			log_progress_msg "$DESC is not running but pid file exists, cleaning up"
		elif [ $? -eq 3 ]; then
			PID="`cat $BLZG_PID`"
			log_failure_msg "Failed to stop $NAME (pid $PID)"
			exit 1
		fi
		rm -f "$BLZG_PID"
		rm -rf "$JVM_TMP"
	else
		log_progress_msg "(not running)"
	fi
	log_end_msg 0
	set -e
	;;
  status)
	status_of_proc -p $BLZG_PID "$JAVA_HOME/bin/java" "$NAME" && exit 0 || exit $?
    ;;
  restart|force-reload)
	if [ -f "$BLZG_PID" ]; then
		$0 stop
		sleep 1
	fi
	$0 start
	;;
  try-restart)
        if start-stop-daemon --test --start --pidfile "$BLZG_PID" \
			--user $BLZG_USER --exec "$JAVA_HOME/bin/java" \
			>/dev/null; then
		$0 start
	fi
    ;;
  *)
	log_success_msg "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
